version: '3'
services:
  app:
    command: npm run server
    build: .
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/src:/workspace/src
      - /workspace/node_modules
    environment:
      PORT: 3000
